### PR TITLE
Removed Serilog added LibLog

### PR DESCRIPTION
**Pull request by scardetto**
---
Rebus is [MIT-licensed](https://opensource.org/licenses/MIT). The code submitted in this pull request needs to carry the MIT license too. By leaving this text in, __I hereby acknowledge that the code submitted in the pull request has the MIT license and can be merged with the Rebus codebase__.

A couple of notes:

- I replaced the Serilog formatting...
    `_logger.Debug("Stopping service {ServiceName}", service.Name);` 
    ...with simple string interpolation.
    `_logger.Debug($"Stopping service {service.Name}");`
    Not sure if there was a specific reason for using the Serilog facility for that.

- I replaced the global static `Serilog.Log` instance in `ServiceHost` with a log scoped to the `ServiceHost` class.  i.e. `LogProvider.GetCurrentClassLogger()` However, it might make more sense to have a single "Topper" log instance used by everyone instead of declaring them by class i.e. `LogProvider.GetLogger("Topper")`.  What do you think?

- I added a dependency on the `Topshelf.LibLog` package as a replacement for `Topshelf.Serilog`

- I took a crack at updating the README. Not crazy about it. :)

### CODE REVIEW

**Comment by mookid8000** [comment]
Hi @scardetto , I think the CLA assistant is unable to recognize you... it says to [add the email address used for the commit to your GitHub account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user)

**Comment by scardetto** [comment]
It's added.  Sorry about that. :(

**Comment by mookid8000** [comment]
Excellent 😄 let's see if CLA assistant can pick it up....

**Comment by mookid8000** [comment]
@scardetto now that you have added your email address, you should be able to click on the CLA assistant thing somewhere and sign it. This is a requirement for all "rebus-org" repositories to be able to retain their MIT licenses and not have its license polluted by contributions from people

**Comment by scardetto** [comment]
When I click the link, it says I have already signed it.

Here's a screenshot...

Screenshot

Maybe there is a way to reset it?

Sorry for all the trouble.

**Comment by mookid8000** [comment]
Hmm, looks like it got confused 😁 

No worries, I'll keep this PR and your screenshot as an ownership transfer statement.

**Comment by mookid8000** [comment]
Thank you for the contribution – it's out in 2.0.0 on NuGet.org in a few minutes

**Pull request merged**
